# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 478)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.lst_contacts = QtWidgets.QListView(Form)
        self.lst_contacts.setMinimumSize(QtCore.QSize(250, 0))
        self.lst_contacts.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lst_contacts.setObjectName("lst_contacts")
        self.gridLayout.addWidget(self.lst_contacts, 0, 0, 1, 1)
        self.txt_send = QtWidgets.QPlainTextEdit(Form)
        self.txt_send.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txt_send.setObjectName("txt_send")
        self.gridLayout.addWidget(self.txt_send, 4, 1, 1, 1)
        self.txt_search = QtWidgets.QPlainTextEdit(Form)
        self.txt_search.setMinimumSize(QtCore.QSize(250, 0))
        self.txt_search.setMaximumSize(QtCore.QSize(250, 25))
        self.txt_search.setObjectName("txt_search")
        self.gridLayout.addWidget(self.txt_search, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_remove = QtWidgets.QPushButton(Form)
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout.addWidget(self.btn_remove)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.txt_chat = QtWidgets.QTextEdit(Form)
        self.txt_chat.setObjectName("txt_chat")
        self.gridLayout.addWidget(self.txt_chat, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_send = QtWidgets.QPushButton(Form)
        self.btn_send.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_2.addWidget(self.btn_send)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Chat"))
        self.btn_add.setText(_translate("Form", "+"))
        self.btn_remove.setText(_translate("Form", "-"))
        self.btn_send.setText(_translate("Form", "Отправить"))
