# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialog_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Tuple
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(427, 133)
        self.verticalLayout2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setObjectName("label2")
        self.verticalLayout.addWidget(self.label2)
        self.lineEdit2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit2.setObjectName("lineEdit2")
        self.verticalLayout.addWidget(self.lineEdit2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добро пожаловать"))
        self.label.setText(_translate("Dialog", "Введите login:"))
        self.label2.setText(_translate("Dialog", "Введите пароль:"))


class DialogWindow(QDialog):
    def __init__(self, parent=None, login: str = ""):
        super().__init__(parent)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.ui.lineEdit.setText(login)

    def get_text(self) -> Tuple[str, str]:
        return self.ui.lineEdit.text(), self.ui.lineEdit2.text()
